version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kun_khmer_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kun_khmer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: betpro-backend
    container_name: kun_khmer_backend_laravel
    restart: always
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: php artisan serve --host=0.0.0.0 --port=3001
    depends_on:
      - postgres

volumes:
  postgres_data:
